### ISSUE TITLE
Missing profile for Ubuntu 16.04.2

### ISSUE THREAD

**Issue by hehnope** [google/rekall-profiles#21]

**Comment by macuisdein** [comment]
I can confirm your bug. The Makefile doesn't specify when using "make profile" to copy the pmem.ko file to the specific version pmem-4.4.0-72-generic.ko, so the zip is failing

> zip "4.4.0-72-generic.zip" module_dwarf.ko /boot/System.map-4.4.0-72-generic /boot/config-4.4.0-72-generic "pmem-4.4.0-72-generic.ko"
	zip warning: name not matched: pmem-4.4.0-72-generic.ko

I am submitting a patch, but in the meantime, you can manually fix it by running:
`sudo cp pmem.ko pmem$(name -r).ko`
and then:
`zip "$(KVER).zip" module_dwarf.ko $(KSYSTEMMAP) $(KCONFIG) "pmem-$(KVER).ko"`

or modifying the Makefile on line 28 from:

`profile: dwarf`
to:
`profile: dwarf pmem`

**Comment by jersten** [comment]
I rebuilt the profile using `profile: dwarf pmem` method without issue.

I tried to read from the memory dump and got:

```python
Traceback (most recent call last):
  File "/usr/local/bin/rekal", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 95, in main
    user_session=user_session)
  File "/usr/local/lib/python2.7/dist-packages/rekall/args.py", line 430, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 138, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 947, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 413, in is_active
    profile = (session.profile != None and
  File "/usr/local/lib/python2.7/dist-packages/rekall/utils.py", line 1009, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 1055, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 733, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename ../laptop.vmem.
```

Thats a memory dump from `linpmem`.

**Comment by cesar-rickinho** [comment]
I can confirm that I'm having the same issue with a copy from master downloaded today on Ubuntu 16.04.2 release 4.10.0-42-generic. Can anybody help troubleshoot and fix?

**Comment by scudette** [comment]
Be aware that you can not currently take memory images using linpmem from linux systems which have CONFIG_RANDOMIZE_MEMORY enabled. That option causes /proc/kcore to be randomized and linpmem does not currently handle that properly.

You can take the image using rekall:
```
rekal aff4acquire myimage.aff4
```

Because Rekall is able to unrandomize /proc/kcore since https://github.com/google/rekall/commit/985bb875f23b85d851396292cf45d2ac7f55d6cc

There were some requests to add that logic to linpmem but it is not a high priority since rekall is a far better imaging tool anyway (it can also acquire files).

**Comment by bbb31** [comment]
Are you saying that you cant make a profile properly because of linpmem?

**Comment by cesar-rickinho** [comment]
No @bbb31, sorry for not being more specific, I am able to create the profile, but I'm another able to capture the memory using linpmem. Capturing the memory with linpmem was returning me a 33TB file on a 1GB ram VM and 1GB swap file. 

I'll follow @scudette advice and try to capture the dump with rekall and report the results.

**Comment by scudette** [comment]
No - im saying that linpmem does not acquire (all) the correct memory ranges because they are randomized so it is likely the image is partial. Please check this is what is happening though - on the system you should be able to do:
```
# readelf -a /proc/kcore
...
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  NOTE           0x00000000000004a0 0x0000000000000000 0x0000000000000000
                 0x0000000000001954 0x0000000000000000         0x0
  LOAD           0x00007fffff602000 0xffffffffff600000 0xffffffffffffffff
                 0x0000000000001000 0x0000000000001000  RWE    0x1000
  LOAD           0x00007fff88402000 0xffffffff88400000 0x0000000014c00000
                 0x000000000154e000 0x000000000154e000  RWE    0x1000
..
 LOAD           0x00000b9080003000 0xffff8b9080001000 0x0000000000001000
                 0x000000000009c000 0x000000000009c000  RWE    0x1000
...
```

Compare with /proc/iomem (The last range matches with the first System Ram region because its size is right).

```
root@elite:~/rekall# cat /proc/iomem
00000000-00000fff : Reserved
00001000-0009dbff : System RAM
```

The random offset is 0xffff8b9080001000-0x00001000 = 0xffff8b9080000000

But as you can see here https://github.com/google/rekall/blob/master/tools/pmem/linux_pmem.cc#L74 linpmem has that hard coded at 0xffff880000000000. So it will discard some of the memory regions from acquisition.
